---
title: "Panarchy: ripples of a boundary concept"
author: |
  | \small \textbf{Juan C. Rocha}
  | \small Stockholm Resilience Centre
  | \small Stockholm University
  | \small \texttt{\href{mailto:juan.rocha@su.se}{\nolinkurl{juan.rocha@su.se}}}


abstract: |
  Ecosystems around the world are at riks of critical transitions due to increasing anthropogenic preasures and climate change [@Bolt:2018ib; @Rocha:2018gn; @Rockstrom:2009p4681; @Steffen:2018ku]. However, it is not clear where this risks are higher or where ecosystems are more vulnerable. Here I measure resilience of primary production proxies for marine and terrestrial ecosystems globally.

bibliography: panarchy.bib
csl: nature.csl
output:
  pdf_document:
    dev: pdf
    keep_tex: no
    toc: no
    latex_engine: xelatex
  word_document:
    toc: no
citecolor: blue
documentclass: article
font: Arial
fontsize: 10pt

linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{dcolumn, rotating, longtable, lineno, float, fontspec, array, tabularx}
- \setmainfont{Arial}
- \linenumbers
- \renewcommand{\abstractname}{}
- \graphicspath{{figures/}}
- \usepackage[margin=2.5cm]{geometry}
---

# Outline
Intro
-  What is Panarchy and how it has influenced the scholarly of sustainability scientist in the last 2 decades?
    - Key features: adaptive cycles nested in scales, poverty and rigidity traps.
    - How have these concepts developed in the last 2 decades?
    - What are the key frontiers of research?

- Method
    - Literature review (coded by humans)
    - topic modelling on WoS searches and all papers that have been cited Holling's summary
- Results

# Introduction
(800w)
Panarchy encapsulates a set of concepts that have inspired the work of environmental scientist and practitioners for almost two decades. It is the product of a group of scientists interested in solving environmental issues by integrating insights from the social and natural sciences, as well as the arts and humanities. Panarchy was, and still is, a boundary object that has enable collaborations and nurture new scientific frameworks. The ideas put forward have found applications in field studies, mathematical models, participatory work, and scenario development. It has inspired resilience assessments and guided decision making. In this article we pay tribute to the book by studying how the concepts and metaphors proposed have been further developed in the academic literature. We also document the criticism to the concepts and identify key research frontiers.

Panarchy is not a theory of what it is, but a metaphor of what might be [@Gunderson:2002vk]. It is not a predictive tool, but aims to understand adaptive change. Panarchy posits that systems are organised in nested hierarchies across space and time. Each level of the hierarchy is a subsystem that can be in different phases of adaptive cycles. These phases are exploitation, conservation, release, and reorganization. They are inspired in mathematical models used in economics and ecology, but broadly describe patterns of growth, collapse, and recovery that are common to populations, ecological communities, markets, or political organizations. While each subsystem in scale can be at different phases of the cycle, they can influence each other through cross-scale interactions namely revolt and remember.

The adaptive cycle is hypothesized to exist in a three-dimensional space that integrates three key systemic features: its potential, connectivity, and resilience [@Gunderson:2002vk]. The potential refers to the available capital to the system, which can be approximated as nutrients and carbon captured by a diverse forest, or the human capital of skills and knowledge accumulated to run an economy. Connectivity is a proxy of the structure of the system, it is the network of interactions and strength between its elements. Resilience is the capacity of any system to absorb disturbance and reorganise while undergoing change so as to still retain essentially the same function, structure, feedbacks, and therefore identity [@Anonymous:2016fv].

The three-dimensional space has corners with attractors that can stagnate the adaptive cycle: poverty and rigidity traps [@Gunderson:2002vk]. In panarchy, poverty traps are described as maladptive states where potential, connectivity and resilience is low. Poverty traps are a series of feedback mechanisms that reinforce inpoverish states [@Bowles:2006hx], limiting the capacity to innovate and increase potential. The opposite corner where potential, connectivity and resilience are high are also a maladaptive space denoted as rigidity traps. In that space there is little space for experimentation and innovation such a very conservative and bureaucratic systems.

Panarchy offers a rich conceptual framework to think of environmental problems. While inspired in a few mathematical constructs (e.g. cycles, traps, scaling laws), it is general enough to invite scholars from multiple disciplinary backgrounds, ontologies and epistemologies, to collaborate around research questions and applied problems. It is a boundary object. The book itself presents a series of case studies where geographers, economists, political scientist, and ecologist have found the framework useful. However, to what extent have these concepts gained empirical support beyond the metaphor, how these concepts have evolved, and are we at a stage where we can start deriving theories remind open questions. For example, the adaptive cycle is a useful metaphor to look back at history and organize events and periods around phases. It reminds challenging however to narrow down in what phase is a system in the present, or what would be its expected trajectory in the future. In other words, it seems useufl in retrospective studies, but its application more limited for prospective ones.

Here we review the academic literature of the last two decades with the aim of tracing how these concepts have evolved, in what type of problems are they found useful, and what remain key frontiers of research.

[Figure 1 -- Panarchy conceptual figure? ]

# Methods
(800w)

To answer these questions we combined an automated literature review based on topic modelling with human-coded document analysis.

*Data*: We used the Web of Science, Scopus, and GoogleScholar to survey academic literature that has used or referenced works that trace back to Panarchy [@Gunderson:2002vk]. We extracted complete records from the Web of Science that matched the search for "(panarchy OR adaptive cycle) AND resilience" (N=XX). The data was combined with all papers (N = 1379) that cited the inaugural paper that introduced the book to the academic community [Holling]. Records with missing abstracts were dropped (N=XX), and records with missing year were set to 2020 given that they are accepted manuscripts with digital object identifier (doi) scheduled to be published later in 2020 or 2021.

To prepare the data for topic modelling, we constructed a document term matrix with documents in rows and words in columns. Here our unit of analysis for the document are the abstracts retrieved, and the matrix contain the count of words per document. We removed stop words (e.g. "the", "a") and digits from the matrix, as well as a list of words that were over represented in our data (e.g. "paper", "study", "aim") that are common in the scientific literature but do not inform us about the topics the papers are about.

*Topic models*: are an unsupervised statistical technique to reduce the dimensionality of a corpus of data (typically but not necessarily text) into topics [@Blai]. Here a topic is a latent variable that ranks words with high probability of appearing together within the same document. Documents in turn can be described by the probability that is is described by a particular set of topics. Since they are (posterior) probabilities, the sum of the probability of all words for any given topic should be one, and the sum of the probability of all topics for any given document should also be one. An iterative process or algorithm is what allows the model to learn the ranking of words that best explain topics, and the ranking of topics that best explain documents.

The underlying statistical technique for this machine learning approach is called Latent Dirichlet Allocation (LDA) [@Blei]. It allocates probabilites to latent variables (topics) based on the distribution of words in text data, assuming a multivariate continuous (Dirichlet) distribution. We compared three LDA algorithms: correlated topic models (CTM), variational expectation maximization (VEM), and Gibbs sampling (Gibbs), by assessing their performance against their log-likelihood estimation, entropy and perplexity [@tmodels]. These metrics enable us to choose which algorithm best fit our data, what is the optimal number of topics to fit, and how to avoid overfitting.

*Document analysis*: We complemented our unsupervised approach with document analysis [] by coding an additional set of categorical variables for a subsample of papers (N = XX). We annotated qualitative aspects such as use of the adaptive cycle, identification of its phases, whether the paper is conceptual, modelling or empirical; or the temporal and spatial scales of the case study. We also identified what aspects of panarchy were most used in the papers. For example whether there is emphasis on cross-scale interactions, or poverty and rigidity traps. Text annotations were used to capture potential criticisms as well as the methods used. The code book is available in the supplementary material (archived in XX repository).

# Results
(1000w)

Panarchy, the book published in 2002, has been cited over 7200 times according to Google Scholar. The scientific paper that introduced the book to the scientific community [@HOlling] has received 1715 citations in the Web of Science, and 1923 in Scopus. Roughly half of the citations comes from environmental (28%) and social sciences (22%), while the less represented fields are computer science (2.1%), arts and humanities (2.6%).

# Discussion
(1000w)


# Conclusion
(400w)


# References {-}
\bibliography{references}


\pagebreak

# Supplementary Material
